### PR TITLE
Noticed my subclassing patch didn't make it into the last release.

### PR DESCRIPTION
**Pull request by jmmills**
And, I noticed that you are on github now so I just forked and respun it.
I don't know if if you remember but iirc we spoke about this one on IRC.
I use nopaste everyday so if there is anything else you want help with let me know :)

### CODE REVIEW

**Comment by jmmills** [comment]
ping?

**Comment by jmmills** [comment]
Hello?

**Comment by sartak** [comment]
Sorry for taking so long. Thank you!

**Comment by jmmills** [comment]
Awesome, hopefully this will make it easier to add additional command line/configuration file parameters for finer grain control on different paste services (such as gist vs pastebin).
I know for me I will no longer have to maintain a fork for my organization to utilize our internal paste service :)

**Pull request merged**
